### PR TITLE
Fix for issue #11: Doesn't work correctly with compiler generated state machines

### PR DESCRIPTION
**Pull request by techjoshua**

### CODE REVIEW

**Comment by SimonCropp** [comment]
can u add a test that verifies thi

**Comment by techjoshua** [comment]
While this fix does work I'm questioning whether it goes too far or not.

For generic types, it should be fine.  For generic methods in non-generic types it make be overcompensating as it looks for all nested generic type of the containing type which have a generic parameter with the same name.  Since the parameter name can be reused between generic methods and not all generic methods which use the name "T" may not have been intended to be declared with the enum or delegate constraint attribute.

The problem here is that the compiler leaves us no indication, aside from a CompilerGeneratedAttribute and some cryptic internal naming scheme that is unique to the MS compiler and may change, that a given generated class or method or field was generated from a particular method that had a generic type parameter which had this attribute.

The code which I'm currently using to achieve similar results causes the generic type parameter to extend an IEnumConstraint interface (which is empty).  The benefit here is that the compiler carries this clue throughout it's generated code for us, and we're able to find and replace it very easily.  This is how the original Uncostrained Melody code worked as well... my primary difference is that I've created msbuild targets to take care of calling ildasm / ilasm.

My code ends up looking like this:
public class SomethingEnumRelated<T> where T : struct
#if UNCONSTRAINED
    , IEnumConstraint
#endif
{

}

Was hoping to make use of your much easier to understand and maintain attribute approach but I'm doubting that it can be done with 100% certainty.

**Comment by SimonCropp** [comment]
So abandon this attempt?

**Comment by techjoshua** [comment]
I'm not saying to abandon it, but perhaps it needs to be modified... Looking at what the compiler preserves as it creates these generated classes and methods it would seem that you are limited to either using the generic type name or an existing generic type constraint.

Unconstrained Melody used the generic type constraint, but perhaps you could use the generic type name.  Perhaps we could assume TEnum and TDelegate represent Enum and Delegate types.  Or perhaps we could require the author to attribute, at the class level, what type names match which desired constraint:

```
[GenericEnumTypeName("TEnum")]
[GenericDelegateTypeName("TDelegate")]
public static class SomeClass
{
    public static TEnum ParseEnum<TEnum>(this string val, TEnum defaultVal = default(TEnum))
    where TEnum : struct, new() // would be replaced by Enum constraint
    {
        TEnum result;
        if (!Enum.TryParse<TEnum>(val, true, out result))
        {
            return defaultVal;
        }

        return result;
    }

    public TDelegate Combine<TDelegate> (this TDelegate first, params TDelegate[] delegates)
    {
        return (TDelegate)Delegate.Combine(new [] { first }.Concat(delegates));
    }
}
```

That would allow the developer to limit the scope of a particular generic type parameter name to a given class or possibly an assembly.  It would also give them the flexibility to give names that match their naming conventions.

Additionally it would allow us to find the exact enum / delegate constraints we need to change, either in the entire assembly or in a given class.

**Comment by SimonCropp** [comment]
@techjoshua can u ping me directly on simon.cropp@gmail.com ? I have something else i want to dicuss

**Pull request closed without merging**
